// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiOVSmbZ1zjJR1GDCyH09F-j9ItkYXlK4',
    appId: '1:171000343724:web:d84be7347c0f334dca4309',
    messagingSenderId: '171000343724',
    projectId: 'final-project-odc',
    authDomain: 'final-project-odc.firebaseapp.com',
    storageBucket: 'final-project-odc.firebasestorage.app',
    measurementId: 'G-9GT35QH93W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByGSaf4LO8MacyTPSJqnTLv5TDJNqVzIM',
    appId: '1:171000343724:android:c00bc7c742c6d68aca4309',
    messagingSenderId: '171000343724',
    projectId: 'final-project-odc',
    storageBucket: 'final-project-odc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWYoul-oR-uDUy3ZDsJbOj4gAAK9HySdo',
    appId: '1:171000343724:ios:c030dee761fab65bca4309',
    messagingSenderId: '171000343724',
    projectId: 'final-project-odc',
    storageBucket: 'final-project-odc.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectOdc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWYoul-oR-uDUy3ZDsJbOj4gAAK9HySdo',
    appId: '1:171000343724:ios:c030dee761fab65bca4309',
    messagingSenderId: '171000343724',
    projectId: 'final-project-odc',
    storageBucket: 'final-project-odc.firebasestorage.app',
    iosBundleId: 'com.example.finalProjectOdc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiOVSmbZ1zjJR1GDCyH09F-j9ItkYXlK4',
    appId: '1:171000343724:web:75683ec24827c176ca4309',
    messagingSenderId: '171000343724',
    projectId: 'final-project-odc',
    authDomain: 'final-project-odc.firebaseapp.com',
    storageBucket: 'final-project-odc.firebasestorage.app',
    measurementId: 'G-F2Y4NSMYPY',
  );
}
